HW4 finish
kobaserg/nodejs-homework-rest-api pull request #3
Opened 2023-02-03 15:30 UTC by kobaserg

Добрий вечір. Перевірте, будь ласка, мою роботу. Все працює коректно. Чекаю на коментарі.

2023-02-03 19:32 UTC, Eastvarga requested changes
Дуже багато зауважень

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/contactsController.js
> +  res.status(201).json({ newContacts, status: "Add contact successfully" });
res.status(201).json(newContacts) достатньо для відповіді

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/contactsController.js
> +  res.status(200).json({ removeId, status: "Delete contact successfully" });
Краще повертайте видалений контакт.
Як гадаєте чому метод мангуста при видаленні повертає контакт?

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/contactsController.js
> +  res.status(200).json({ id, body, status: "Update contact successfully" });
теж саме - 
await serviceContact.updateContact(req); - повинно повертати результат соєї дії - доданий контакт
await serviceContact.updateContact(**req**)  req - запит\відповідь не повинні потрапляти до сервісів - тільки необхідні данні повинні туби потрапити
const id = req.params.id;
const updateDto = req.body;
const newContact = await updateContactService(id, updateDto)

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/contactsController.js
> +    .json({ id, body, status: "Contacts Favorite status change successfully" });
Звідкіля така логіка повертати у відповіді те, що потрапило з запиту, а де перевірка чи відповідає це тому що є у базі у такому разі? Тому зазвичай повертають об'єкт результат роботи оновлення у базі

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/usersController.js
> +    status: `Signup with email : ${email} and password : ${password} successfully`,
А Вас не вчили креди юзера не віддавати назовні у чистому вигляді, а саме пароль?

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/usersController.js
> +      password,
а навіщо пароль відавати? Це не потрібно

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/usersController.js
> +};
Ви точно дивились матеріали?
Це якась дикість.
У вас є мідлвар аутентикації, котрий працює з токеном, та у разі успішної валідації записує до запиту у поле user об'єкт юзера. А отже надалі у наступних мідлварах або контролері поточного раута Ви зможете юзера узяти з 
const user = req.user

2023-02-03 19:32 UTC, Eastvarga commented on src/controllers/usersController.js
> +  const user = await serviceUsers.userSubsciption(req);
const user = await serviceUsers.userSubsciption(**req**); req - не повинно потрапляти до сервісів - тільки контроллер знає що таке запит та все необхідне для сервісів вилучає з запиту та передає до сервісів

2023-02-03 19:32 UTC, Eastvarga commented on src/middlewares/userMiddleware.js
> +  const [, token] = authorization.split(" ");
Де забули "Bearer"? Цю частину теж варто перевіряти бо хедер повинен мати вигляд "Bearer SomeTokenThere"

2023-02-03 19:32 UTC, Eastvarga commented on src/middlewares/userMiddleware.js
> +    const { _id } = jwt.verify(token, process.env.JWT_SECRET);
process.env.JWT_SECRET - усі змінні середовища варто виокремити до файлу в котрому їх ініціалізувати та потім імпортувати туди де вони потрібні

2023-02-03 19:32 UTC, Eastvarga commented on src/middlewares/userMiddleware.js
> +    req.token = token;
токен не потрібен у запиті - це зайве достатньо юзера

2023-02-03 19:32 UTC, Eastvarga commented on src/routers/usersRouter.js
> +  userTokenMiddleware,
authMidleware - краще по змісту назва підходить

2023-02-03 19:32 UTC, Eastvarga commented on src/routers/usersRouter.js
> +  asyncWrapper(getUserContactsController)
у цьму контролері getUserContactsController - можна просто повернути юзера без запиту до бази, бо він у Вас вже є післі роботи userTokenMiddleware у полі **req.user** . Подумайте про це

2023-02-03 19:32 UTC, Eastvarga commented on src/routers/usersRouter.js
> +
чому немає userTokenMiddleware?

2023-02-03 19:32 UTC, Eastvarga commented on src/routers/usersRouter.js
> +  asyncWrapper(userSubscriptionController)
Чи перевіряли Ви роботу цього ендпоінту?

2023-02-03 19:32 UTC, Eastvarga commented on src/services/contactsService.js
> +  verifyErrorById(id, contact);
Не розумію навіщо це, якщо хочете валідувати айді, то створіть валідацію айді у запиті, а що це за постфактум валідація, щось дивне та не логічне

2023-02-03 19:32 UTC, Eastvarga commented on src/services/usersService.js
> +  return token;
ось тут краще повертати токен та юзер айді - цей айді фронт використає вже для запиту деталей юзера після логіну

2023-02-03 19:32 UTC, Eastvarga commented on src/services/usersService.js
> +};
це не потрібно бо після мідлвару авторизації юзер зберігається у req.user

2023-02-03 19:32 UTC, Eastvarga commented on src/services/usersService.js
> +  const { email, password, subscription } = req.body;
зміна підписки не потребує email, password, лише токена у хедері та subscription  у тілі запиту , а отже ваш сервіс не працює - чи перевіряли ви його логіку та дію?

2023-02-03 19:32 UTC, Eastvarga commented on src/services/usersService.js
> +    throw new NotAuthorizedError(`Wrong password: '${password}' `);
зовсім зайве - для цього є мідлвар аутентифікації!

2023-02-03 21:46 UTC, kobaserg commented
Виправив

2023-02-04 10:32 UTC, Eastvarga requested changes
Треба доопрацювати

2023-02-04 10:32 UTC, Eastvarga commented on src/controllers/contactsController.js
> +  res.status(201).json({ newContacts });
res.status(201).json(newContacts); ось  так краще  -  не потрібно повертати об'єкт у полі newContacts достатньо сам об'єкт повернути, інколи що правда використовують поле data- але це роблять для синхронізування взаємодії з фреймворком де у полі може бути різні данні.
  Спробуйте з цим розібратись

2023-02-04 10:32 UTC, Eastvarga commented on src/controllers/usersController.js
> +  res.status(200).json({ email, token, status: "Current user successfully" });
const { email, subscription } = req.user
res.status(200).json( { email, subscription });
щось таке потрібно було зробити,
те що ви зробили дуже невдале рішення.
токен юзер отримає лише прі логіні та ніяк інакше - Ви порушуєте безпеку застосунку роздаючи токен або пароль у інших раутах

2023-02-04 10:32 UTC, Eastvarga commented on src/controllers/usersController.js
> +  await serviceUsers.userSubsciption(token, subscription);
тут не зробили виправлення - отримали запит, перевірили його, виконали потрібні дії (оновлення юзера) - вам повернула БД новий об'єкт як результат оновлення - ви віддали необхідні данні з цього об'єкту у відповідь.

2023-02-04 12:43 UTC, kobaserg commented
Наче все виправив. В усіх джерелах інформації по темах є відхилення в практуванні того чи іншого. Деякі речі роблю на свій розсуд, тому даруйте, що забираю на себе трохи більше вашого часу.

2023-02-04 18:15 UTC, Eastvarga approved these changes

2023-02-04 18:16 UTC, merged