HW5 finish before control
kobaserg/nodejs-homework-rest-api pull request #4
Opened 2023-02-15 18:34 UTC by kobaserg

Добрий вечір. Тест робив по маршруту signup. Треба, напевно моки використовувати, бо тест реально добавляє в базу користувача, або треба використовувати для тестів окремі теки в базах даних.

2023-02-16 15:44 UTC, Eastvarga requested changes
Є зауваження

2023-02-16 15:44 UTC, Eastvarga commented on app.js
> +const avatarsDIR = path.resolve("public");
зайве. Достатньо вказати відносний шлях
app.use(express.static("public")); 
тут тека public повинна бути у середині кореня проекту на тому ж рівні що й package.json

2023-02-16 15:44 UTC, Eastvarga commented on app.js
> +app.use("/avatars", avatarsImageRouter);
Аватари юзера, отже за завданням аватари повинні бути всередині
app.use("/api/users", usersRouter);

2023-02-16 15:44 UTC, Eastvarga commented on src/controllers/usersController.js
> +  const avatarURL = path.join("public", "avatars", resultName);
невірно, не використовуйте модуль що призначений для файлової системи для генерації URL link бо поведінка модуля залежить від файлової системи, а код повинен генерувати однаковий результат незалежно від файлової системи. Отриманий вами результат не схожий на 
 http://locahost:<порт>/avatars/<ім'я файлу з розширенням> `

2023-02-16 15:44 UTC, Eastvarga commented on src/middlewares/authMiddleware.js
> +    req.token = token;
навіщо токен вам надалі?
Він потрібен лише у мідлварі авторизації далі Ви отримали юзера, і про токен забули

2023-02-16 16:27 UTC, kobaserg commented on app.js
> +app.use("/avatars", avatarsImageRouter);
Аватари юзера всередені users.       /avatars -- шлях до перегляду статіки  згідно з п.1 домашнього завдання

2023-02-16 16:29 UTC, kobaserg commented on app.js
> +const avatarsDIR = path.resolve("public");
попробую

2023-02-16 16:30 UTC, kobaserg commented on src/controllers/usersController.js
> +  const avatarURL = path.join("public", "avatars", resultName);
згоден. не знав і не думав. дякую. перероблю

2023-02-16 16:31 UTC, kobaserg commented on src/middlewares/authMiddleware.js
> +    req.token = token;
згоген. зроблю. дякую за ретельно перевірену роботу

2023-02-17 07:29 UTC, kobaserg commented on app.js
> +const avatarsDIR = path.resolve("public");
виправив, працює

2023-02-17 07:40 UTC, kobaserg commented on src/controllers/usersController.js
> +  const avatarURL = path.join("public", "avatars", resultName);
Він і не повинен бути схожий на http://locahost/:<порт>/avatars/<ім'я файлу з розширенням> ` . Це шлях до /api/users/avatars -- заміна аваратки , а http://locahost/:<порт>/avatars/<ім'я файлу з розширенням> ` -- перегляд аватарки зі статики

2023-02-17 08:05 UTC, kobaserg commented on src/controllers/usersController.js
> +  const avatarURL = path.join("public", "avatars", resultName);
модуль path не використовую, сформував відносний шлях. працює

2023-02-17 17:11 UTC, Eastvarga commented on app.js
> +app.use("/avatars", avatarsImageRouter);
Хм, Ви в омані.
app.use("/api/users", usersRouter); шлях для ендпоінту завантаження аватарів на сервер повинен бути на рівні дій з юзером, отже всередині рауту /api/users, а не окремий раут
Окремий раут каже нам що то можуть бути будьякі аватари хоч контактів хоч юзерів, тоб-то не прив'язаних до когось. Але за завданням це аватари юзера и райт повинен бути /api/users/avatars.
Ось це і треба Вам виправити

2023-02-17 17:20 UTC, Eastvarga requested changes
Є зауваження

2023-02-17 17:20 UTC, Eastvarga commented on src/controllers/usersController.js
> +  const avatarURL = "public" + "/avatars/" + resultName;
"public" + "/avatars/" + resultName;
заменіть "public" на HOST = process.env.SERVERHOST | | `http://localhost:${PORT}`
потім завантажте свою аватарку, а отриману лінку скопіюйте та вставте у браузер, якщо Ваш сервер працює, і Ви зробили все вірно, то Ви отримаєте аватарку у браузері (сервер Вам її віддасть), якщо ні - Ви щось невірно робите

2023-02-17 17:20 UTC, Eastvarga commented on app.js
>  app.use("/api/users", usersRouter);
обробку раута /avatars перенесіть у рауе /api/users щоб завантаження аватара було по рауту  /api/users/avatars

2023-02-17 18:10 UTC, kobaserg commented on app.js
> +app.use("/avatars", avatarsImageRouter);
мене ввела в оману умова домашнього завдання: http://localhost:<порт>/avatars/<имя файла с расширением>. тут шлях прописаний без users,  тому робив так . вважаю, що умова в домашньому завданні некоректна. перероблюю

2023-02-18 07:23 UTC, kobaserg commented
Дякую за допомогу та ретельну перевірку домашки. Все переробив, все гаразд і все працює. З express.static розібрався.

2023-02-18 09:51 UTC, Eastvarga requested changes
Є зауваження

2023-02-18 09:51 UTC, Eastvarga commented on src/routers/usersRouter.js
> +router.get("/avatars/:avatar", asyncWrapper(avatarImageController));
Ось цей костиль навіщо? Ваші аватарки повинні віддаватись зі статики а не з Цього рауту.
Видаліть теку http:/localhost:8000/avatars Бо через неї Ваш репозіторій не клонується (там де каритнка)
Пушити картинки з теки аватарс у репозіторій не треба зовсім.
Зараз Ваш код генерує начебто вірний url тому мені не зрозуміло нащо цей раут

2023-02-19 11:45 UTC, Eastvarga approved these changes

2023-02-19 11:45 UTC, merged